# Generated by Django 4.1.6 on 2023-02-05 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_alter_newuser_managers_newuser_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='passenger',
        ),
        migrations.AddField(
            model_name='driver',
            name='is_driver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='newuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
