# Generated by Django 4.1.6 on 2023-02-05 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_remove_newuser_driver_remove_newuser_passenger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='is_passenger',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='rating',
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_normal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricNo', models.CharField(max_length=10)),
                ('isDriver', models.BooleanField(default=False)),
                ('isPassenger', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffNo', models.CharField(max_length=255)),
                ('isDriver', models.BooleanField(default=False)),
                ('isPassenger', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
