# Generated by Django 4.1.6 on 2023-02-05 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_remove_driver_is_driver_remove_driver_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='newuser',
            name='matricNo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='staffNo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
